# -*- coding: utf-8 -*-

sponsor_list = [
    { 'id': 95133, 'tag': 'sonoma', 'name': "sonoma" },
    { 'id': 41781, 'tag': 'roomflavor', 'name': "ルームフレーバー" },
    { 'id': 55121, 'tag': 'chiyoda', 'name': "靴専門店チヨダオンラインショップ" },
    { 'id': 47536, 'tag': 'nipponcolumbia-games', 'name': "日本コロムビア ＜ゲーム＞" },
    { 'id': 54620, 'tag': 'actus', 'name': "ACTUS" },
    { 'id': 49784, 'tag': 'tokyu-hands', 'name': "東急ハンズ" },
    { 'id': 46714, 'tag': 'momastore', 'name': "MoMA STORE" },
    { 'id': 46984, 'tag': 'generatedesign', 'name': "Generate" },
    { 'id': 41704, 'tag': 'kenzo', 'name': "KENZO" },
    { 'id': 44655, 'tag': 'zariganiworks', 'name': "ザリガニワークス" },
    { 'id': 44824, 'tag': 'tokyolife', 'name': "TOKYOlife" },
    { 'id': 53816, 'tag': 'house-wf', 'name': "ハウスウェルネスフーズ" },
    { 'id': 47809, 'tag': 'laundry', 'name': "LAUNDRY" },
    { 'id': 52019, 'tag': 'yonnana-club', 'name': "47CLUB" },
    { 'id': 54512, 'tag': 'midori', 'name': "ミドリ オンラインストア" },
    { 'id': 60408, 'tag': 'hightide', 'name': "HIGHTIDE" },
    { 'id': 35553, 'tag': 'hibiyakadan', 'name': "日比谷花壇" },
    { 'id': 45719, 'tag': 'collectivestore', 'name': "コレクティブストア" },
    { 'id': 53834, 'tag': 'nakagawa', 'name': "中川政七商店" },
    { 'id': 56882, 'tag': 'plazastyle', 'name': "PLAZA" },
    { 'id': 47456, 'tag': 'monodo', 'name': "monoDO" },
    { 'id': 59512, 'tag': 'ropepicnic', 'name': "Ropé Picnic Official onlineshop" },
    { 'id': 54355, 'tag': 'karelcapek', 'name': "カレルチャペック紅茶店" },
    { 'id': 58736, 'tag': 'efilose', 'name': "Efilose" },
    { 'id': 46552, 'tag': 'kinto', 'name': "キントー" },
    { 'id': 57689, 'tag': 'mederu_jewelry', 'name': "mederu jewelry" },
    { 'id': 48142, 'tag': 'sekaimon', 'name': "セカイモン" },
    { 'id': 49501, 'tag': 'rocketnews24', 'name': "ロケットニュース" },
    { 'id': 53538, 'tag': 'garage', 'name': "Garage" },
    { 'id': 44060, 'tag': 'beebeebaby', 'name': "ベビー服、ベビー用品の「Bee Bee Baby」" },
    { 'id': 46057, 'tag': 'mitsubai', 'name': "密買東京" },
    { 'id': 52805, 'tag': 'living-motif', 'name': "リビング・モティーフ" },
    { 'id': 54360, 'tag': 'fobcoop', 'name': "F.O.B COOP" },
    { 'id': 46518, 'tag': 'mujilife', 'name': "無印良品" },
    { 'id': 41635, 'tag': 'tokyokaikan', 'name': "東京會舘" },
    { 'id': 56409, 'tag': 'junkudo_net', 'name': "ジュンク堂書店" },
    { 'id': 56250, 'tag': 'lmaga', 'name': "京阪神エルマガジン社" },
    { 'id': 52867, 'tag': 'vanilla', 'name': "バニラ家具" },
    { 'id': 52868, 'tag': 'kinaru', 'name': "インテリアショップ・キナル" },
    { 'id': 50231, 'tag': 'ito-ya', 'name': "伊東屋" },
    { 'id': 57341, 'tag': 'fusosha', 'name': "扶桑社" },
    { 'id': 53494, 'tag': 'plantsplus', 'name': "plants+" },
    { 'id': 48507, 'tag': 'happinet', 'name': "ハピネット" },
    { 'id': 53599, 'tag': 'yamada-bee-farm', 'name': "山田養蜂場" },
    { 'id': 49681, 'tag': 'kagome', 'name': "カゴメ" },
    { 'id': 46568, 'tag': 'kusatsu', 'name': "草津温泉" },
    { 'id': 47568, 'tag': 'idea', 'name': "イデアのデザインで話す" },
    { 'id': 48089, 'tag': 'louisvuitton', 'name': "LOUIS VUITTON ルイ・ヴィトン" },
    { 'id': 53879, 'tag': 'smilith', 'name': "国産のオシャレな木製犬小屋「Smilith」" },
    { 'id': 54414, 'tag': 'econamise', 'name': "エコナミセ" },
    { 'id': 51953, 'tag': 'shokuninnotakumi', 'name': "職人の匠" },
    { 'id': 45601, 'tag': 'lomography', 'name': "LOMO" },
    { 'id': 53260, 'tag': 'potager', 'name': "ポタジエ" },
    { 'id': 53276, 'tag': 'thekiss', 'name': "THE KISS" },
    { 'id': 46985, 'tag': 'addsuperb', 'name': "アッドスパーブ" },
    { 'id': 45425, 'tag': 'kokuyo', 'name': "コクヨ" },
    { 'id': 50095, 'tag': 'tivoli', 'name': "Tivoli Audio" },
    { 'id': 49255, 'tag': 'iejima', 'name': "伊江もの本舗" },
    { 'id': 48471, 'tag': 'uniquestandards', 'name': "ユニークスタンダーズ" },
    { 'id': 50621, 'tag': 'goma-books', 'name': "ゴマブックス" },
    { 'id': 51481, 'tag': 'airbuggy', 'name': "AirBuggy" },
    { 'id': 51003, 'tag': 'piebooks', 'name': "ピエ・ブックス" },
    { 'id': 47545, 'tag': 'tokuma-shoten', 'name': "徳間書店“ほん”のちょこっといい話" },
    { 'id': 42756, 'tag': 'planted', 'name': "PLANTED" },
    { 'id': 44767, 'tag': 'pen', 'name': "pen［ペン］" },
    { 'id': 44549, 'tag': 'hankyu-communications', 'name': "阪急コミュニケーションズ" },
    { 'id': 47592, 'tag': 'petit', 'name': "プチグラ" },
    { 'id': 47421, 'tag': 'choco-cafe', 'name': "100％ChocolateCafe." },
    { 'id': 47000, 'tag': 'tagboat', 'name': "@Gallery TAGBOAT" },
    { 'id': 48420, 'tag': 'zoff', 'name': "Ｚｏｆｆ" },
    { 'id': 48359, 'tag': 'dreamcatalog', 'name': "ドリームカタログ" },
    { 'id': 47015, 'tag': 'soli-chara', 'name': "そりっどちゃらいあんす" },
    { 'id': 48559, 'tag': 'mediaseven', 'name': "メディアセブン" },
    { 'id': 45173, 'tag': 'imaging-park', 'name': "Imaging-Park" },
    { 'id': 46081, 'tag': 'otokonokakuregaonline', 'name': "男の隠れ家ＯＮＬＩＮＥ" },
    { 'id': 45524, 'tag': 'gasas-if', 'name': "ガスアズインターフェイス" },
    { 'id': 48858, 'tag': 'plato', 'name': "えいご漬け" },
    { 'id': 45529, 'tag': 'miyazakich', 'name': "みやざきWEBチャンネル" },
    { 'id': 47466, 'tag': 'shopgnavi', 'name': "ぐるなび食市場" },
    { 'id': 48411, 'tag': 'auau', 'name': "アザラシの「あうあう！」" },
    { 'id': 46760, 'tag': 'yujin', 'name': "ユージン" },
    { 'id': 48175, 'tag': 'nanoca', 'name': "フェリシモ" },
    { 'id': 47762, 'tag': 'uogashi3', 'name': "築地魚河岸三代目" },
    { 'id': 45736, 'tag': 'tvkshop', 'name': "ｔｖｋショップ" },
    { 'id': 47699, 'tag': 'isobe', 'name': "純喫茶磯辺" },
    { 'id': 45683, 'tag': 'hitoseku', 'name': "人のセックスを笑うな" },
    { 'id': 44599, 'tag': 'edays', 'name': "e-days" },
    { 'id': 40290, 'tag': 'bunkamura', 'name': "Bunkamura ザ・ミュージアム" },
    { 'id': 44967, 'tag': 'lush', 'name': "LUSH" },
    { 'id': 44493, 'tag': 'airkaol', 'name': "エアーかおる" },
    { 'id': 43004, 'tag': 'wacom', 'name': "ワコム" },
    { 'id': 42959, 'tag': 'rakuten', 'name': "楽天市場×関心ストア" },
    { 'id': 41944, 'tag': 'asahibeer', 'name': "アサヒビール" },
    { 'id': 40018, 'tag': 'ebank', 'name': "イーバンク銀行" },
    { 'id': 40577, 'tag': 'jal', 'name': "JAL" },
    { 'id': 40507, 'tag': 'caffelatte', 'name': "マウントレーニア　カフェラッテ" },
    { 'id': 40532, 'tag': 'sekisuiheim', 'name': "セキスイハイム" },
    { 'id': 40199, 'tag': 'eo', 'name': "eo光" },
    { 'id': 40307, 'tag': 'gmark', 'name': "グッドデザイン賞" },
    { 'id': 39807, 'tag': 'horti', 'name': "Horti" },
    { 'id': 38395, 'tag': 'starflyer', 'name': "スターフライヤー" },
    { 'id': 34675, 'tag': 'kinshoku', 'name': "錦食伝説" },
    { 'id': 34918, 'tag': 'buyma', 'name': "バイマ" },
    { 'id': 35980, 'tag': 'nioh', 'name': "仁王" },
]

def find(tag):
    for sponsor in sponsor_list:
        if tag == sponsor['tag']:
            return sponsor
    return None

def find_id(tag):
    sponsor = find(tag)
    return sponsor['id'] if sponsor else None

