# -*- coding: utf-8 -*-

sponsor_list = [
    { 'id': 95133, 'tag': u'sonoma', 'name': u"sonoma" },
    { 'id': 41781, 'tag': u'roomflavor', 'name': u"ルームフレーバー" },
    { 'id': 55121, 'tag': u'chiyoda', 'name': u"靴専門店チヨダオンラインショップ" },
    { 'id': 47536, 'tag': u'nipponcolumbia-games', 'name': u"日本コロムビア ＜ゲーム＞" },
    { 'id': 54620, 'tag': u'actus', 'name': u"ACTUS" },
    { 'id': 49784, 'tag': u'tokyu-hands', 'name': u"東急ハンズ" },
    { 'id': 46714, 'tag': u'momastore', 'name': u"MoMA STORE" },
    { 'id': 46984, 'tag': u'generatedesign', 'name': u"Generate" },
    { 'id': 41704, 'tag': u'kenzo', 'name': u"KENZO" },
    { 'id': 44655, 'tag': u'zariganiworks', 'name': u"ザリガニワークス" },
    { 'id': 44824, 'tag': u'tokyolife', 'name': u"TOKYOlife" },
    { 'id': 53816, 'tag': u'house-wf', 'name': u"ハウスウェルネスフーズ" },
    { 'id': 47809, 'tag': u'laundry', 'name': u"LAUNDRY" },
    { 'id': 52019, 'tag': u'yonnana-club', 'name': u"47CLUB" },
    { 'id': 54512, 'tag': u'midori', 'name': u"ミドリ オンラインストア" },
    { 'id': 60408, 'tag': u'hightide', 'name': u"HIGHTIDE" },
    { 'id': 35553, 'tag': u'hibiyakadan', 'name': u"日比谷花壇" },
    { 'id': 45719, 'tag': u'collectivestore', 'name': u"コレクティブストア" },
    { 'id': 53834, 'tag': u'nakagawa', 'name': u"中川政七商店" },
    { 'id': 56882, 'tag': u'plazastyle', 'name': u"PLAZA" },
    { 'id': 47456, 'tag': u'monodo', 'name': u"monoDO" },
    { 'id': 59512, 'tag': u'ropepicnic', 'name': u"Ropé Picnic Official onlineshop" },
    { 'id': 54355, 'tag': u'karelcapek', 'name': u"カレルチャペック紅茶店" },
    { 'id': 58736, 'tag': u'efilose', 'name': u"Efilose" },
    { 'id': 46552, 'tag': u'kinto', 'name': u"キントー" },
    { 'id': 57689, 'tag': u'mederu_jewelry', 'name': u"mederu jewelry" },
    { 'id': 48142, 'tag': u'sekaimon', 'name': u"セカイモン" },
    { 'id': 49501, 'tag': u'rocketnews24', 'name': u"ロケットニュース" },
    { 'id': 53538, 'tag': u'garage', 'name': u"Garage" },
    { 'id': 44060, 'tag': u'beebeebaby', 'name': u"ベビー服、ベビー用品の「Bee Bee Baby」" },
    { 'id': 46057, 'tag': u'mitsubai', 'name': u"密買東京" },
    { 'id': 52805, 'tag': u'living-motif', 'name': u"リビング・モティーフ" },
    { 'id': 54360, 'tag': u'fobcoop', 'name': u"F.O.B COOP" },
    { 'id': 46518, 'tag': u'mujilife', 'name': u"無印良品" },
    { 'id': 41635, 'tag': u'tokyokaikan', 'name': u"東京會舘" },
    { 'id': 56409, 'tag': u'junkudo_net', 'name': u"ジュンク堂書店" },
    { 'id': 56250, 'tag': u'lmaga', 'name': u"京阪神エルマガジン社" },
    { 'id': 52867, 'tag': u'vanilla', 'name': u"バニラ家具" },
    { 'id': 52868, 'tag': u'kinaru', 'name': u"インテリアショップ・キナル" },
    { 'id': 50231, 'tag': u'ito-ya', 'name': u"伊東屋" },
    { 'id': 57341, 'tag': u'fusosha', 'name': u"扶桑社" },
    { 'id': 53494, 'tag': u'plantsplus', 'name': u"plants+" },
    { 'id': 48507, 'tag': u'happinet', 'name': u"ハピネット" },
    { 'id': 53599, 'tag': u'yamada-bee-farm', 'name': u"山田養蜂場" },
    { 'id': 49681, 'tag': u'kagome', 'name': u"カゴメ" },
    { 'id': 46568, 'tag': u'kusatsu', 'name': u"草津温泉" },
    { 'id': 47568, 'tag': u'idea', 'name': u"イデアのデザインで話す" },
    { 'id': 48089, 'tag': u'louisvuitton', 'name': u"LOUIS VUITTON ルイ・ヴィトン" },
    { 'id': 53879, 'tag': u'smilith', 'name': u"国産のオシャレな木製犬小屋「Smilith」" },
    { 'id': 54414, 'tag': u'econamise', 'name': u"エコナミセ" },
    { 'id': 51953, 'tag': u'shokuninnotakumi', 'name': u"職人の匠" },
    { 'id': 45601, 'tag': u'lomography', 'name': u"LOMO" },
    { 'id': 53260, 'tag': u'potager', 'name': u"ポタジエ" },
    { 'id': 53276, 'tag': u'thekiss', 'name': u"THE KISS" },
    { 'id': 46985, 'tag': u'addsuperb', 'name': u"アッドスパーブ" },
    { 'id': 45425, 'tag': u'kokuyo', 'name': u"コクヨ" },
    { 'id': 50095, 'tag': u'tivoli', 'name': u"Tivoli Audio" },
    { 'id': 49255, 'tag': u'iejima', 'name': u"伊江もの本舗" },
    { 'id': 48471, 'tag': u'uniquestandards', 'name': u"ユニークスタンダーズ" },
    { 'id': 50621, 'tag': u'goma-books', 'name': u"ゴマブックス" },
    { 'id': 51481, 'tag': u'airbuggy', 'name': u"AirBuggy" },
    { 'id': 51003, 'tag': u'piebooks', 'name': u"ピエ・ブックス" },
    { 'id': 47545, 'tag': u'tokuma-shoten', 'name': u"徳間書店“ほん”のちょこっといい話" },
    { 'id': 42756, 'tag': u'planted', 'name': u"PLANTED" },
    { 'id': 44767, 'tag': u'pen', 'name': u"pen［ペン］" },
    { 'id': 44549, 'tag': u'hankyu-communications', 'name': u"阪急コミュニケーションズ" },
    { 'id': 47592, 'tag': u'petit', 'name': u"プチグラ" },
    { 'id': 47421, 'tag': u'choco-cafe', 'name': u"100％ChocolateCafe." },
    { 'id': 47000, 'tag': u'tagboat', 'name': u"@Gallery TAGBOAT" },
    { 'id': 48420, 'tag': u'zoff', 'name': u"Ｚｏｆｆ" },
    { 'id': 48359, 'tag': u'dreamcatalog', 'name': u"ドリームカタログ" },
    { 'id': 47015, 'tag': u'soli-chara', 'name': u"そりっどちゃらいあんす" },
    { 'id': 48559, 'tag': u'mediaseven', 'name': u"メディアセブン" },
    { 'id': 45173, 'tag': u'imaging-park', 'name': u"Imaging-Park" },
    { 'id': 46081, 'tag': u'otokonokakuregaonline', 'name': u"男の隠れ家ＯＮＬＩＮＥ" },
    { 'id': 45524, 'tag': u'gasas-if', 'name': u"ガスアズインターフェイス" },
    { 'id': 48858, 'tag': u'plato', 'name': u"えいご漬け" },
    { 'id': 45529, 'tag': u'miyazakich', 'name': u"みやざきWEBチャンネル" },
    { 'id': 47466, 'tag': u'shopgnavi', 'name': u"ぐるなび食市場" },
    { 'id': 48411, 'tag': u'auau', 'name': u"アザラシの「あうあう！」" },
    { 'id': 46760, 'tag': u'yujin', 'name': u"ユージン" },
    { 'id': 48175, 'tag': u'nanoca', 'name': u"フェリシモ" },
    { 'id': 47762, 'tag': u'uogashi3', 'name': u"築地魚河岸三代目" },
    { 'id': 45736, 'tag': u'tvkshop', 'name': u"ｔｖｋショップ" },
    { 'id': 47699, 'tag': u'isobe', 'name': u"純喫茶磯辺" },
    { 'id': 45683, 'tag': u'hitoseku', 'name': u"人のセックスを笑うな" },
    { 'id': 44599, 'tag': u'edays', 'name': u"e-days" },
    { 'id': 40290, 'tag': u'bunkamura', 'name': u"Bunkamura ザ・ミュージアム" },
    { 'id': 44967, 'tag': u'lush', 'name': u"LUSH" },
    { 'id': 44493, 'tag': u'airkaol', 'name': u"エアーかおる" },
    { 'id': 43004, 'tag': u'wacom', 'name': u"ワコム" },
    { 'id': 42959, 'tag': u'rakuten', 'name': u"楽天市場×関心ストア" },
    { 'id': 41944, 'tag': u'asahibeer', 'name': u"アサヒビール" },
    { 'id': 40018, 'tag': u'ebank', 'name': u"イーバンク銀行" },
    { 'id': 40577, 'tag': u'jal', 'name': u"JAL" },
    { 'id': 40507, 'tag': u'caffelatte', 'name': u"マウントレーニア　カフェラッテ" },
    { 'id': 40532, 'tag': u'sekisuiheim', 'name': u"セキスイハイム" },
    { 'id': 40199, 'tag': u'eo', 'name': u"eo光" },
    { 'id': 40307, 'tag': u'gmark', 'name': u"グッドデザイン賞" },
    { 'id': 39807, 'tag': u'horti', 'name': u"Horti" },
    { 'id': 38395, 'tag': u'starflyer', 'name': u"スターフライヤー" },
    { 'id': 34675, 'tag': u'kinshoku', 'name': u"錦食伝説" },
    { 'id': 34918, 'tag': u'buyma', 'name': u"バイマ" },
    { 'id': 35980, 'tag': u'nioh', 'name': u"仁王" },

    { 'id': 51190, 'tag': u'comicbeamiiwai', 'name': u"コミックビーム　岩井っス" },
    { 'id': 48050, 'tag': u'kataokayoshiro', 'name': u"片岡義朗" },
    { 'id': 54409, 'tag': u'junji-naito', 'name': u"内藤順司" },
    { 'id': 47163, 'tag': u'takeshitadaigaku', 'name': u"育種家 竹下大学" },
    { 'id': 9569, 'tag': u'dayorin', 'name': u"ダヨリン" },
    { 'id': 54064, 'tag': u'yagyushingo', 'name': u"柳生真吾" },
]

def find(tag):
    for sponsor in sponsor_list:
        if tag == sponsor['tag']:
            return sponsor
    return None

def find_id(tag):
    sponsor = find(tag)
    return sponsor['id'] if sponsor else None

